name: Create Tutorial Workspace

on:
  pull_request:
    branches: ["main"]
    types:
      - labeled
      - synchronize

jobs:
  deploy-preview:
    if: contains(github.event.pull_request.labels.*.name, 'Workspace')
    runs-on: ubuntu-latest

    env:
      VONAGE_API_KEY: 'febe6726'
      VCR_REGION: 'euw1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: get-changed-files
        uses: tj-actions/changed-files@v45

      - name: Get changed folder
        id: get-changed-folder
        env:
          ALL_CHANGED_FILES: ${{ steps.get-changed-files.outputs.all_changed_files }}
        run: |
          first_file=$(echo "$ALL_CHANGED_FILES" | awk '{print $1}')
          top_level_dir=$(echo "$first_file" | cut -d'/' -f1,2)
          echo "dir=$top_level_dir" >> "$GITHUB_OUTPUT"

      - name: Check for config file
        working-directory: ${{ steps.get-changed-folder.outputs.dir }}
        run: |
          pwd
          if [ ! -f tutorial-config.json ]; then
            echo "tutorial-config.json not found. Exiting."
            exit 1
          fi

      - name: Create Workspace Folder
        working-directory: ${{ steps.get-changed-folder.outputs.dir }}
        run: |
          mkdir ws
          cd ws
          pwd
          cp ../tutorial-config.json .
          cp -r $GITHUB_WORKSPACE/DummyWorkspace/. .
          cp $GITHUB_WORKSPACE/createworkspace.sh .
          ls -a
          ./createworkspace.sh https://google.com //TODO move link generation into script

      - name: Zip Release
        id: zip-release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: "zip"
          directory: "${{ steps.get-changed-folder.outputs.dir }}/ws"
          path: "."
          filename: "release.zip"
          exclusions: "tutorial-config.json"

      - name: Upload a Build Artifact
        id: upload-release-artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          path: "${{ steps.get-changed-folder.outputs.dir }}/ws/release.zip"      

      - name: Leave comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const artifactURL = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Your artifact is ready: [Download it here](${artifactURL})`
            });
