name: Create Tutorial Workspace

on:
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  create-workspace:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      VONAGE_API_KEY: 'febe6726'
      VCR_REGION: 'euw1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: get-changed-files
        uses: tj-actions/changed-files@v45

      - name: Get changed folder
        id: get-changed-folder
        env:
          ALL_CHANGED_FILES: ${{ steps.get-changed-files.outputs.all_changed_files }}
        run: |
          first_file=$(echo "$ALL_CHANGED_FILES" | awk '{print $1}')
          top_level_dir=$(echo "$first_file" | cut -d'/' -f1,2)
          echo "dir=$top_level_dir" >> "$GITHUB_OUTPUT"

      - name: Check for config file
        working-directory: ${{ steps.get-changed-folder.outputs.dir }}
        run: |
          pwd
          if [ ! -f tutorial-config.json ]; then
            echo "tutorial-config.json not found. Exiting."
            exit 1
          fi

      - name: Create Workspace Folder
        working-directory: ${{ steps.get-changed-folder.outputs.dir }}
        run: |
          mkdir ws
          cd ws
          pwd
          cp ../tutorial-config.json .
          cp -r $GITHUB_WORKSPACE/DummyWorkspace/. .
          cp $GITHUB_WORKSPACE/createworkspace.sh .
          ls -a
          ./createworkspace.sh

      - name: Tag the commit
        id: tag-commit
        working-directory: ${{ steps.get-changed-folder.outputs.dir }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add --all

          slug=$(jq -r '.slug' tutorial-config.json)
          version=$(jq -r '.version' tutorial-config.json)
          TAG_NAME="${slug}-v${version}"

          git commit -m "Adding workspace for ${TAG_NAME}"
          git tag -a $TAG_NAME -m "Tagging commit for version ${TAG_NAME}"

          git push
          git push origin $TAG_NAME

          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Zip Workspace
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: "zip"
          directory: "${{ steps.get-changed-folder.outputs.dir }}/ws"
          path: "."
          filename: "ws.zip"
          exclusions: "tutorial-config.json, createworkspace.sh"

      - name: Upload a Build Artifact
        id: upload-release-artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          path: "${{ steps.get-changed-folder.outputs.dir }}/ws/ws.zip"    

      - name: Create release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.get-changed-folder.outputs.dir }}/ws/ws.zip"
          body: "https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}"
          tag: "refs/tags/${{ steps.tag-commit.outputs.tag_name }}"
